repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.11.5"
    hooks:
      - id: ruff-format
      - id: ruff
  - repo: https://github.com/MarcoGorelli/cython-lint
    rev: v0.16.6
    hooks:
      - id: cython-lint
      - id: double-quote-cython-strings