repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.15.16"
    hooks:
      - id: ruff-format
      - id: ruff-check
  - repo: https://github.com/MarcoGorelli/cython-lint
    rev: v0.19.0
    hooks:
      - id: cython-lint
      - id: double-quote-cython-strings