name: pyogrio
channels:
  - conda-forge
dependencies:
  - python==3.10.*
  - gdal
  - numpy==1.24.*
  - numpydoc==1.1.*
  - Cython==0.29.*
  - docutils==0.16.*
  - myst-parser
  - pip
  - pip:
      - sphinx_rtd_theme
