name: pyogrio
channels:
  - conda-forge
dependencies:
  - python==3.9.*
  - gdal
  - numpy==1.19.*
  - numpydoc==1.1.*
  - Cython==0.29.*
  - docutils==0.16.*
  - myst-parser
  - pip
  - pip:
      - sphinx_rtd_theme
