name: Build wheels

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v1
        id: vcpkgcache
        with:
          path: C:/vcpkg/installed
          key: ${{ runner.os }}-vcpkg

      - name: Install GDAL
        run: |
          vcpkg install gdal[core]:x64-windows

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.3.1
        # env:
        #   CIBW_SOME_OPTION: value

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl

  windows-tests:
    name: windows py${{ matrix.python-version }} tests
    runs-on: windows-latest
    needs: build_wheels
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]
        include:
          - os: windows-latest
            triplet: x64-windows

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: false

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Download wheels from artifacts
        uses: actions/download-artifact@v2
        with:
          path: wheelhouse

      - name: Set version string
        shell: bash
        run: echo "py_version_str=cp$(echo ${{ matrix.python-version }} | tr -d -c 0-9)" >> $GITHUB_ENV

      - name: Get wheel name
        shell: bash
        run: echo "wheel_name=$(ls -R wheelhouse/ | grep whl)" >> $GITHUB_ENV

      - name: Install package from wheel
        shell: bash
        run: |
          ls -R wheelhouse
          python -m pip install --upgrade pip
          python -m pip install wheelhouse/artifact/${{ env.wheel_name }}
      - name: Run tests
        run: |
          python -m pip install pytest
          python -m pip list
          cd ..
          python -m pytest --pyargs pyogrio
